8 UI display health and bullets
gliganii/wilderprophunt pull request #10
Opened 2023-11-03 22:14 UTC by abrindea

2023-11-03 22:44 UTC, projektd3us approved these changes

2023-11-03 22:44 UTC, ErsinianArmando approved these changes

2023-11-03 23:44 UTC, wilderpodiwan requested changes

2023-11-03 23:44 UTC, wilderpodiwan commented on healthBar.tscn
> +text = "100"
the text should be computed, based on a variable in the player instance, instead of being hardcoded

2023-11-04 14:03 UTC, wilderpodiwan approved these changes

2023-11-04 14:04 UTC, merged